// Generates src/generated/mercos.ts from the committed OpenAPI document. Types only, no runtime.
import { mkdirSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { SPEC_FILE } from "./lib/docs.ts";

const OUTPUT = "src/generated/mercos.ts";
const HEADER = `// Generated by scripts/gen-types.ts from ${SPEC_FILE}. Do not edit by hand.\n\n`;

// The pages leave many objects with no properties declared. That means "not described", not "empty".
const ast = await openapiTS(pathToFileURL(SPEC_FILE), { alphabetize: true, emptyObjectsUnknown: true });
mkdirSync("src/generated", { recursive: true });
writeFileSync(OUTPUT, HEADER + astToString(ast));
console.log(`Types written to ${OUTPUT}.`);
