// Merges the OpenAPI fragments from the cached pages into a single committed document.
// Each page carries the document for one operation only, with messy path keys. This script
// normalizes them, drops the drafts, and applies the manual fixes from spec/patches.json.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { BASE_URLS } from "../src/client.ts";
import { extractOpenApi, readIndex, SPEC_FILE } from "./lib/docs.ts";

type Json = Record<string, unknown>;

interface Patches {
  /** By page slug: the real path of an operation published under a draft key. */
  paths: Record<string, string>;
  /** By page slug: the variant name when two operations share a path and a method. */
  variants: Record<string, string>;
  /** Targeted fixes to the final document, by JSON Pointer. One fact, one entry. */
  set: { pointers: string[]; value: unknown; reason: string }[];
}

const METHODS = new Set(["get", "post", "put", "delete", "patch"]);
const TOKEN_HEADERS = new Set(["applicationtoken", "companytoken"]);

const patches = JSON.parse(readFileSync("spec/patches.json", "utf8")) as Patches;

/** "/v1/eventos/-1-1" and "/v1/clientes?alterado_apos= " become "/v1/eventos" and "/v1/clientes". */
function normalizePath(key: string): string {
  return key
    .replace(/\?.*$/, "")
    .trim()
    .replace(/(-\d+)+$/, "")
    .replace(/\/+$/, "");
}

function operationId(method: string, path: string): string {
  return `${method}_${path}`
    .replace(/[{}]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

function setPointer(doc: Json, pointer: string, value: unknown): void {
  const keys = pointer
    .split("/")
    .slice(1)
    .map((key) => key.replace(/~1/g, "/").replace(/~0/g, "~"));
  let node = doc;
  for (const key of keys.slice(0, -1)) {
    if (typeof node[key] !== "object" || node[key] === null)
      throw new Error(`Invalid pointer in patches.json: ${pointer}`);
    node = node[key] as Record<string, unknown>;
  }
  node[keys.at(-1)!] = value;
}

const paths: Record<string, Json> = {};
const notes: string[] = [];
let operations = 0;

for (const page of readIndex()) {
  if (!existsSync(page.file)) throw new Error(`Page missing from the cache: ${page.file}. Run "pnpm spec:fetch".`);
  const fragment = extractOpenApi(readFileSync(page.file, "utf8"));
  if (!fragment) continue;

  for (const [rawPath, item] of Object.entries(fragment.paths as Record<string, Json>)) {
    for (const [method, rawOperation] of Object.entries(item)) {
      if (!METHODS.has(method)) continue;
      const path = patches.paths[page.slug] ?? normalizePath(rawPath);
      if (!/^\/v\d+\//.test(path)) {
        notes.push(`dropped (draft with no fix): ${method.toUpperCase()} ${rawPath} [${page.slug}]`);
        continue;
      }

      let key = path;
      if (paths[key]?.[method]) {
        key = `${path}#${patches.variants[page.slug] ?? page.slug}`;
        if (!patches.variants[page.slug]) notes.push(`variant with no name in patches.json: ${key}`);
        if (paths[key]?.[method]) throw new Error(`Unresolved collision: ${method.toUpperCase()} ${key}`);
      }

      const operation = rawOperation as Json;
      const parameters = ((operation.parameters as Json[] | undefined) ?? []).filter(
        (parameter) => !(parameter.in === "header" && TOKEN_HEADERS.has(String(parameter.name).toLowerCase())),
      );
      paths[key] ??= {};
      paths[key][method] = {
        ...operation,
        operationId: operationId(method, key),
        summary: operation.summary ?? page.title,
        externalDocs: { url: page.url.replace(/\.md$/, "") },
        parameters: parameters.length > 0 ? parameters : undefined,
      };
      operations++;
    }
  }
}

const document: Json = {
  openapi: "3.0.3",
  info: {
    title: "Mercos integration API",
    version: "1.0.0",
    description:
      "Unofficial document, assembled from the fragments published at docs.mercos.com. " +
      "Generated by scripts/merge-spec.ts. Do not edit by hand; use spec/patches.json.",
  },
  servers: [
    { url: BASE_URLS.sandbox, description: "Sandbox" },
    { url: BASE_URLS.production, description: "Production" },
  ],
  security: [{ ApplicationToken: [], CompanyToken: [] }],
  paths: Object.fromEntries(Object.entries(paths).sort(([a], [b]) => a.localeCompare(b))),
  components: {
    securitySchemes: {
      ApplicationToken: { type: "apiKey", in: "header", name: "ApplicationToken" },
      CompanyToken: { type: "apiKey", in: "header", name: "CompanyToken" },
    },
  },
};

for (const patch of patches.set) for (const pointer of patch.pointers) setPointer(document, pointer, patch.value);

writeFileSync(SPEC_FILE, `${JSON.stringify(document, null, 2)}\n`);
for (const note of notes) console.warn(`warning: ${note}`);
console.log(`${operations} operations across ${Object.keys(paths).length} paths written to ${SPEC_FILE}.`);
